Models/ErrorViewModel.cs
using System;

namespace DemoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoApp.Models;

namespace DemoApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Scenario1Controller.cs
using DemoApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.Controllers
{
    public class Scenario1Controller : Controller
    {
        private readonly Database _database;

        public Scenario1Controller(Database database)
        {
            _database = database;
        }

        public IActionResult Index()
        {
            return View(_database.Customers);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _database.Customers.RemoveAll(customer => customer.Id == id);

            return NoContent();
        }
    }
}

Controllers/Scenario2Controller.cs
using DemoApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.Controllers
{
    public class Scenario2Controller : Controller
    {
        private readonly Database _database;

        public Scenario2Controller(Database database)
        {
            _database = database;
        }

        public IActionResult Index()
        {
            return View(_database.Customers);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _database.Customers.RemoveAll(customer => customer.Id == id);

            return PartialView("_CustomerList", _database.Customers);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
 

Views/Scenario1/Index.cshtml
@using DemoApp.Data
@model List<Customer>

@{
    ViewBag.Title = "Customers";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4>
                                Customers
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-lg list-group-flush list my--4">
                        @foreach(var customer in Model)
                        {
                        <li class="list-group-item px-0">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                    <span class="avatar avatar-lg">
                                        <img src="@customer.Avatar" alt="" class="avatar-img">
                                    </span>
                                </div>
                                <div class="col ml--2">
                                    <h4 class="card-title mb-1">
                                        <a href="#!">@GetCustomerFullName(customer)</a>
                                    </h4>
                                    <p class="card-text small text-muted mb-1">
                                        @customer.EmailAddress
                                    </p>
                                </div>
                                <div class="col-auto">
                                    <form asp-action="Delete" asp-route-id="@customer.Id" data-ajax="true" data-ajax-success="deleteItem(this)">
                                        <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                            Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function deleteItem(form) {
            $(form).parents('li').remove();
        }
    </script>
}

@functions {
    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }
} 

Views/Scenario2/Index.cshtml
@using DemoApp.Data
@model List<Customer>

@{
    ViewBag.Title = "Customers";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div id="CustomerList">
                <partial name="_CustomerList" model="Model"/>
            </div>
        </div>
    </div>
</div>

Views/Scenario2/_CustomerList.cshtml
@using DemoApp.Data
@model List<Customer>

<div class="card mt-5">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col">
                <h4>
                    Customers
                </h4>
            </div>
        </div>
    </div>
    <div class="card-body">
        @if (Model.Count == 0)
        {
            <div class="row justify-content-center text-center">
                <div class="col-12 col-md-10 mt-5">

                    <i class="fa fa-user fa-5x mb-5"></i>

                    <h2>
                        No Customers
                    </h2>

                    <p class="text-muted">
                        You do not have any customers yet. Add a new customer by clicking the <strong>Add Customer</strong> button below.
                    </p>
                    
                    <a class="btn btn-lg btn-primary d-none d-md-inline-block mt-3" href="#">Add Customer</a>
                </div>
            </div> <!-- / .row -->
        }
        else
        {
            <ul class="list-group list-group-lg list-group-flush list my--4">
                @foreach (var customer in Model)
                {
                    <li class="list-group-item px-0">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <span class="avatar avatar-lg">
                                    <img src="@customer.Avatar" alt="" class="avatar-img">
                                </span>
                            </div>
                            <div class="col ml--2">
                                <h4 class="card-title mb-1">
                                    <a href="#!">@GetCustomerFullName(customer)</a>
                                </h4>
                                <p class="card-text small text-muted mb-1">
                                    @customer.EmailAddress
                                </p>
                            </div>
                            <div class="col-auto">
                                <form asp-action="Delete" asp-route-id="@customer.Id" data-ajax="true" data-ajax-update="#CustomerList">
                                    <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        }
    </div>
</div>

@functions {
    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }
} 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - DemoApp</title>

    <!-- Favicon -->
    <link href="/assets/img/brand/favicon.png" rel="icon" type="image/png">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Icons -->
    <link href="/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Argon CSS -->
    <link type="text/css" href="/assets/css/argon.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-default">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home">Ajax Sample</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-default">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Scenario1">
                            <span class="nav-link-inner--text">Scenario 1</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Scenario2">
                            <span class="nav-link-inner--text">Scenario 2</span>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

<main role="main">
    @RenderBody()
</main>
    <!-- Core -->
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/popper/popper.min.js"></script>
    <script src="/assets/vendor/bootstrap/bootstrap.min.js"></script>

    <!-- Theme JS -->
    <script src="/assets/js/argon.js"></script>
    <script src="/assets/js/jquery.unobtrusive-ajax.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>